version: '3.7'
services:
  storage:
    image: redis
    container_name: redis
    ports:
      - '${REDIS_POSRT:-6379}'
    volumes:
      - redis:/data  
  api:
    image: atc-challenge:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      ATC_BASE_URL: http://mock:4000
      REDIS_HOST: storage
      REDIS_PORT: 6379
  mock:
    image: atc-challenge:dev
    command: node /usr/src/app/mock/server.js
    volumes:
      - ./mock:/usr/src/app/mock
    ports:
      - 4000:4000
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 60
      EVENT_PUBLISHER_URL: http://api:3000/events
volumes:
  redis:
    driver: local